// <auto-generated />
using System;
using Book_Price_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Price_Backend.Migrations
{
    [DbContext(typeof(BookPriceContext))]
    partial class BookPriceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Price_Backend.Models.BookPrice", b =>
                {
                    b.Property<decimal?>("AdjustedAssetValue")
                        .HasColumnType("decimal(29, 3)")
                        .HasColumnName("Adjusted Asset Value");

                    b.Property<decimal?>("AdjustedRevenue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Adjusted Revenue");

                    b.Property<decimal?>("BookPrice1")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Book Price");

                    b.Property<string>("ClientName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Client Name");

                    b.Property<string>("Partner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Policynumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("POLICYNUMBER");

                    b.Property<string>("ProductProvider")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Product Provider");

                    b.Property<DateOnly?>("Statementdate")
                        .HasColumnType("date")
                        .HasColumnName("STATEMENTDATE");

                    b.ToTable("Book_Price", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
